### ISSUE TITLE
Tetgen not available in build

### ISSUE THREAD

**Issue by stephanmg** [UG4/tool_tetgen#1]
Following instructions in the README to enable the tool tetgen works, however executing a script with ugshell fails.

Build/Error log on Travis here: [Log](https://travis-ci.org/NeuroBox3D/plugin_CrackGenerator/jobs/442481475)

(Building with -DEMBEDDED_PLUGINS=ON didn't help - should it?)

Any help is kindly appreciated.

**Comment by stephanmg** [comment]
Mh. Anybody?

**Comment by sreiter** [comment]
Hi Stephan,

the tetgen tool is a standalone tool. It simply compiles tetgen and places the tetgen binary in the bin folder. This is different from linking to tetgen.

Linking to the new version of tetgen is problematic, since it is GPL licensed. If you still would like to do so,  the old code should still work. Maybe you have to rename the old cmake option to avoid name clashes.

You could also take a look at how ProMesh is calling the tetgen tool, if it is available.

Regards,
Sebastian

**Comment by stephanmg** [comment]
So can I just enable ProMesh in addition via CMake by:
`-DTARGET=ugshell -DProMesh=ON -Dtetgen=ON`?

**Comment by sreiter** [comment]
No. For more information regarding ProMesh please visit
https://github.com/sreiter/ProMesh
and have a look at
https://github.com/sreiter/ProMesh/blob/master/readme_compilation.txt

**Comment by stephanmg** [comment]
Okay the links you posted don't work but I could find it. 👍 Thank you.

**Comment by sreiter** [comment]
Thanks. Fixed the links.
